### ISSUE TITLE
Add module loader

### ISSUE THREAD

**Issue by willianjusten** [Qualy-org/qualy#1]
Browserify? System? I don't know...

**Comment by kazzkiq** [comment]
What about [Rollup](https://github.com/rollup/rollup)? Seems like a badass tool and uses ES6 module syntax!

**Comment by willianjusten** [comment]
Yeah =)
It's a good choice. Do you want to contribute?

**Comment by jmpas** [comment]
Done #5 
We could add sourcemaps and dev environment settings later

**Comment by kazzkiq** [comment]
I am super busy with a personal (and late) project of mine, but would be glad to help as much as possible! 😄

**Comment by willianjusten** [comment]
No problem guy, it's why we are on opensource world, other people can help also =)
