### ISSUE TITLE
Linter + Push

### ISSUE THREAD

**Issue by willianjusten** [Qualy-org/qualy#13]
We need to verify our linter, because he's analysing vendors also and breaking the hook...

**Comment by jmpas** [comment]
Couldn't reproduce this :|
Which vendor did you install?

The linter is analysing all `src` folder

**Comment by willianjusten** [comment]
Download any extra library and put on src folder. You will see...

**Comment by jmpas** [comment]
ooh, ok
you mean without npm :P

hmm... maybe we should define a folder inside `src` for "extra libraries", and then exclude this folder on linting and other stuffs...
what do you think?

`src/lib`?
