### ISSUE TITLE
[SUGGESTION] Is it possible to use BEM as a style method?

### ISSUE THREAD

**Issue by herus02** [Qualy-org/qualy#14]
I saw in this repository of a guy using BEM in Jade: https://github.com/kizu/bemto/ I want to suggest or make a pull request in the project to upgrade the productivity of the boilerplate, which btw it's very interesting.

**Comment by willianjusten** [comment]
I like to use BEM, but some people don't...
And I don't like the way how this bemto works. I prefer legibility over great abstraction. It's better to write more but everyone understand what are happening...

But thanks for the suggestion =)

We have another issues if you want to help us ^^
