### ISSUE TITLE
include wiredep load bower dependencies

### ISSUE THREAD

**Issue by felipesousa** [Qualy-org/qualy#2]
include wiredep with the gulp-modules to improve the use of bower components.

**Comment by willianjusten** [comment]
I hate bower components...=x

**Comment by felipesousa** [comment]
drug: / had already finished ..: /

**Comment by willianjusten** [comment]
Take a look at this link, explaining [Why you should stop using Bower and how to change to Npm](https://gofore.com/stop-using-bower/).

Hope it helps.
