### ISSUE TITLE
Disable Jade/Pug on a project

### ISSUE THREAD

**Issue by kazzkiq** [Qualy-org/qualy#20]
I'm willing to use Qualy on a project, but would like to remove [Jade/Pug](http://jade-lang.com) as the main HTML rendering tool.

How could I disable it for all my markup files and use plain HTML instead?

**Comment by willianjusten** [comment]
You have to do 2 steps.

1) Remove all jade tasks on [gulpfile](https://github.com/Qualy-org/qualy-front/blob/master/gulpfile.js#L59)

2) Create a simple task that moves html from src to build, something like:

``` js
gulp.task('html', () => {
    gulp.src(srcPaths.html)
        .pipe(plumber())
        .pipe(gulp.dest(buildPaths.html));
});
```

And that's all. Please, let me know if you have any trouble.

**Comment by ribeiroevandro** [comment]
I can take and make this change, moving from jade to pug. What do you think @willianjusten ?

**Comment by willianjusten** [comment]
It's okay to me @ribeiroevandro , it's up to you =D
